const cartFunctions = require("./cart");
const cartItemFunctions = require("./cartItem");
const koFunctions = require("./ko");
const bvfFunctions = require("./bvf");

module.exports = {
  // main Database
  createCart: cartFunctions.createCart,
  getIdListOfCartByField: cartFunctions.getIdListOfCartByField,
  getCartById: cartFunctions.getCartById,
  getCartAggById: cartFunctions.getCartAggById,
  getCartListByQuery: cartFunctions.getCartListByQuery,
  getCartStatsByQuery: cartFunctions.getCartStatsByQuery,
  getCartByQuery: cartFunctions.getCartByQuery,
  updateCartById: cartFunctions.updateCartById,
  updateCartByIdList: cartFunctions.updateCartByIdList,
  updateCartByQuery: cartFunctions.updateCartByQuery,
  deleteCartById: cartFunctions.deleteCartById,
  deleteCartByQuery: cartFunctions.deleteCartByQuery,
  dbScriptCreateCart: cartFunctions.dbScriptCreateCart,
  dbScriptGetCart: cartFunctions.dbScriptGetCart,
  dbScriptUpdateCart: cartFunctions.dbScriptUpdateCart,
  dbScriptDeleteCart: cartFunctions.dbScriptDeleteCart,
  dbScriptListCarts: cartFunctions.dbScriptListCarts,
  createCartItem: cartItemFunctions.createCartItem,
  getIdListOfCartItemByField: cartItemFunctions.getIdListOfCartItemByField,
  getCartItemById: cartItemFunctions.getCartItemById,
  getCartItemAggById: cartItemFunctions.getCartItemAggById,
  getCartItemListByQuery: cartItemFunctions.getCartItemListByQuery,
  getCartItemStatsByQuery: cartItemFunctions.getCartItemStatsByQuery,
  getCartItemByQuery: cartItemFunctions.getCartItemByQuery,
  updateCartItemById: cartItemFunctions.updateCartItemById,
  updateCartItemByIdList: cartItemFunctions.updateCartItemByIdList,
  updateCartItemByQuery: cartItemFunctions.updateCartItemByQuery,
  deleteCartItemById: cartItemFunctions.deleteCartItemById,
  deleteCartItemByQuery: cartItemFunctions.deleteCartItemByQuery,

  createKo: koFunctions.createKo,
  getIdListOfKoByField: koFunctions.getIdListOfKoByField,
  getKoById: koFunctions.getKoById,
  getKoAggById: koFunctions.getKoAggById,
  getKoListByQuery: koFunctions.getKoListByQuery,
  getKoStatsByQuery: koFunctions.getKoStatsByQuery,
  getKoByQuery: koFunctions.getKoByQuery,
  updateKoById: koFunctions.updateKoById,
  updateKoByIdList: koFunctions.updateKoByIdList,
  updateKoByQuery: koFunctions.updateKoByQuery,
  deleteKoById: koFunctions.deleteKoById,
  deleteKoByQuery: koFunctions.deleteKoByQuery,

  createBvf: bvfFunctions.createBvf,
  getIdListOfBvfByField: bvfFunctions.getIdListOfBvfByField,
  getBvfById: bvfFunctions.getBvfById,
  getBvfAggById: bvfFunctions.getBvfAggById,
  getBvfListByQuery: bvfFunctions.getBvfListByQuery,
  getBvfStatsByQuery: bvfFunctions.getBvfStatsByQuery,
  getBvfByQuery: bvfFunctions.getBvfByQuery,
  updateBvfById: bvfFunctions.updateBvfById,
  updateBvfByIdList: bvfFunctions.updateBvfByIdList,
  updateBvfByQuery: bvfFunctions.updateBvfByQuery,
  deleteBvfById: bvfFunctions.deleteBvfById,
  deleteBvfByQuery: bvfFunctions.deleteBvfByQuery,
};
