const mainFunctions = require("./main");

module.exports = {
  // main Database
  createCart: mainFunctions.createCart,
  getIdListOfCartByField: mainFunctions.getIdListOfCartByField,
  getCartById: mainFunctions.getCartById,
  getCartAggById: mainFunctions.getCartAggById,
  getCartListByQuery: mainFunctions.getCartListByQuery,
  getCartStatsByQuery: mainFunctions.getCartStatsByQuery,
  getCartByQuery: mainFunctions.getCartByQuery,
  updateCartById: mainFunctions.updateCartById,
  updateCartByIdList: mainFunctions.updateCartByIdList,
  updateCartByQuery: mainFunctions.updateCartByQuery,
  deleteCartById: mainFunctions.deleteCartById,
  deleteCartByQuery: mainFunctions.deleteCartByQuery,
  dbScriptCreateCart: mainFunctions.dbScriptCreateCart,
  dbScriptGetCart: mainFunctions.dbScriptGetCart,
  dbScriptUpdateCart: mainFunctions.dbScriptUpdateCart,
  dbScriptDeleteCart: mainFunctions.dbScriptDeleteCart,
  dbScriptListCarts: mainFunctions.dbScriptListCarts,
  createCartItem: mainFunctions.createCartItem,
  getIdListOfCartItemByField: mainFunctions.getIdListOfCartItemByField,
  getCartItemById: mainFunctions.getCartItemById,
  getCartItemAggById: mainFunctions.getCartItemAggById,
  getCartItemListByQuery: mainFunctions.getCartItemListByQuery,
  getCartItemStatsByQuery: mainFunctions.getCartItemStatsByQuery,
  getCartItemByQuery: mainFunctions.getCartItemByQuery,
  updateCartItemById: mainFunctions.updateCartItemById,
  updateCartItemByIdList: mainFunctions.updateCartItemByIdList,
  updateCartItemByQuery: mainFunctions.updateCartItemByQuery,
  deleteCartItemById: mainFunctions.deleteCartItemById,
  deleteCartItemByQuery: mainFunctions.deleteCartItemByQuery,

  createKo: mainFunctions.createKo,
  getIdListOfKoByField: mainFunctions.getIdListOfKoByField,
  getKoById: mainFunctions.getKoById,
  getKoAggById: mainFunctions.getKoAggById,
  getKoListByQuery: mainFunctions.getKoListByQuery,
  getKoStatsByQuery: mainFunctions.getKoStatsByQuery,
  getKoByQuery: mainFunctions.getKoByQuery,
  updateKoById: mainFunctions.updateKoById,
  updateKoByIdList: mainFunctions.updateKoByIdList,
  updateKoByQuery: mainFunctions.updateKoByQuery,
  deleteKoById: mainFunctions.deleteKoById,
  deleteKoByQuery: mainFunctions.deleteKoByQuery,

  createBvf: mainFunctions.createBvf,
  getIdListOfBvfByField: mainFunctions.getIdListOfBvfByField,
  getBvfById: mainFunctions.getBvfById,
  getBvfAggById: mainFunctions.getBvfAggById,
  getBvfListByQuery: mainFunctions.getBvfListByQuery,
  getBvfStatsByQuery: mainFunctions.getBvfStatsByQuery,
  getBvfByQuery: mainFunctions.getBvfByQuery,
  updateBvfById: mainFunctions.updateBvfById,
  updateBvfByIdList: mainFunctions.updateBvfByIdList,
  updateBvfByQuery: mainFunctions.updateBvfByQuery,
  deleteBvfById: mainFunctions.deleteBvfById,
  deleteBvfByQuery: mainFunctions.deleteBvfByQuery,
};
